### ISSUE TITLE
Compatibility Issues with Python 3.8.18, Pandas-DQ, and Auto_ViML

### ISSUE THREAD

**Issue by LineaR93** [AutoViML/AutoViML#2]
Hello, I am experiencing compatibility issues in my Python environment, specifically when trying to use Pandas-DQ and Auto_ViML together. I am constrained to using Python version 3.8.18 due to certain dependencies in my project. The core issue revolves around conflicting requirements for NumPy versions between Pandas-DQ and Auto_ViML.

Issues:
Pandas-DQ Dependency: It appears that Pandas-DQ requires NumPy version 1.24.5. However, this version of NumPy is incompatible with other parts of my project.
Auto_ViML Dependency: For Auto_ViML, I need to use NumPy version 1.19.5. This version is not compatible with the required version for Pandas-DQ.
Attempts to Resolve:
I have tried using different versions of these packages but haven't found a compatible set that works with Python 3.8.18.
Upgrading Python beyond version 3.8.18 is not feasible due to other specific dependencies in my project.
Request for Assistance:
I am reaching out to the community for advice or solutions that might help resolve these compatibility issues. Any guidance on how to use both Pandas-DQ and Auto_ViML in the same environment, or suggestions for alternative approaches, would be greatly appreciated.

Thank you in advance for your assistance and suggestions.

**Comment by AutoViML** [comment]
Hi: You might want to experiment with Colab or Kaggle kernels where these libraries work with older python versions.That's one to get around these limitations. Try it and let me know the results.Auto Vimal
    On Thursday, January 4, 2024 at 12:05:55 PM EST, irobyx933 ***@***.***> wrote:  
 
 


Hello, I am experiencing compatibility issues in my Python environment, specifically when trying to use Pandas-DQ and Auto_ViML together. I am constrained to using Python version 3.8.18 due to certain dependencies in my project. The core issue revolves around conflicting requirements for NumPy versions between Pandas-DQ and Auto_ViML.

Issues:
Pandas-DQ Dependency: It appears that Pandas-DQ requires NumPy version 1.24.5. However, this version of NumPy is incompatible with other parts of my project.
Auto_ViML Dependency: For Auto_ViML, I need to use NumPy version 1.19.5. This version is not compatible with the required version for Pandas-DQ.
Attempts to Resolve:
I have tried using different versions of these packages but haven't found a compatible set that works with Python 3.8.18.
Upgrading Python beyond version 3.8.18 is not feasible due to other specific dependencies in my project.
Request for Assistance:
I am reaching out to the community for advice or solutions that might help resolve these compatibility issues. Any guidance on how to use both Pandas-DQ and Auto_ViML in the same environment, or suggestions for alternative approaches, would be greatly appreciated.

Thank you in advance for your assistance and suggestions.
